### ISSUE TITLE
可以集成绕过检测吗？

### ISSUE THREAD

**Issue by catcherxuefeng** [zydou/WeChat-AppImage#1]

**Comment by zydou** [comment]
集成不了，现在只能手动copy `login-detection`目录下的文件到相应位置

**Comment by catcherxuefeng** [comment]
https://aur.archlinux.org/packages/wechat-uos-bwrap  
aur 有个项目可以通过沙盒运行

**Comment by zydou** [comment]
你提到的这个应该是利用bubblewrap做沙盒去骗过微信的发行版检测，但目前AppImage并不支持bwarp，而且AppImage的core dev对集成bwarp并不是很感兴趣，估计以后也不会支持 :(

ref: https://github.com/AppImage/AppImageKit/issues/152#issuecomment-1984606418

**Comment by Jackhr-arch** [comment]
> 集成不了，现在只能手动copy `login-detection`目录下的文件到相应位置

有考虑使用PRoot吗？比如[这个](https://github.com/web1n/wechat-universal-appimage/releasesl)
```bash
exec proot -b $HERE/app/wechat/libuosdevicea.so:/usr/lib/license/libuosdevicea.so \
  -b $HERE/app/license/etc/os-release:/etc/os-release \
  -b $HERE/app/license/etc/lsb-release:/etc/lsb-release \
  -b $HERE/app/license/var/lib/uos-license/.license.json:/var/lib/uos-license/.license.json \
  -b $HERE/app/license/var/uos/.license.key:/var/uos/.license.key \
  $HERE/app/wechat/wechat "$@"
```
