### ISSUE TITLE
大佬,为啥libactivation.so用不起啊

### ISSUE THREAD

**Issue by thd2020** [zydou/WeChat-AppImage#4]
一直出现Failed to load /usr/lib/libactivation.so.

**Comment by zydou** [comment]
什么发行版？

**Comment by thd2020** [comment]
ubuntu 23.10, arm64，难道是架构原因？

**Comment by zydou** [comment]
之前只支持`x86_64`架构，现在添加了`aarch64` (即`arm64`) 架构的，你可以试试: [https://github.com/zydou/WeChat-AppImage/releases/tag/1.0.0.238](https://github.com/zydou/WeChat-AppImage/releases/tag/1.0.0.238)

**Comment by thd2020** [comment]
大佬，问题在libactivation.so,目前腾讯要检测这个文件，但是全网都只有此文件的amd64版本，没有arm64的版本。我编译了很多版本的源码，都不对，看来这个libactivation共享库是腾讯内部的源码了。哎，只有等等公开发行版了。

**Comment by zydou** [comment]
你可以试试[bwarp版](https://aur.archlinux.org/cgit/aur.git/tree/?h=wechat-uos-bwrap)或[flatpak版](https://github.com/web1n/wechat-universal-flatpak)提供的`license.tar.gz`，我验证了一下这两个仓库提供的`license.tar.gz`哈希值是一样的，都是从uos中提取的。

从[bwarp版](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wechat-uos-bwrap)的PKGBUILD来看是支持`amd64`, `arm64`, `loong64`三种架构的，所以他们提供的`license.tar.gz`应该是可以使用的。

license具体安装路径你研究一下这两个地方吧：
- https://github.com/web1n/wechat-universal-flatpak/blob/0f827718ab264aea32d4f1f595fb38c94e043d98/com.tencent.WeChat.yaml#L161-L166
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wechat-uos-bwrap#n112

**Comment by SilenWang** [comment]
我使用上面的license信息成功登录了，解压后额外进行下面的操作。最后的`libuosdevicea.so`是软件包里本来就带的，因此直接软链接。

```bash
sudo mkdir -p /var/lib/uos-license /var/uos/ /usr/lib/license

sudo cp -r ./license/etc/os-release /etc/os-release
sudo cp -r ./license/etc/lsb-release /etc/lsb-release
sudo cp -r ./license/var/lib/uos-license/.license.json /var/lib/uos-license/.license.json
sudo cp -r ./license/var/uos/.license.key /var/uos/

sudo ln -s /opt/apps/com.tencent.wechat/files/libuosdevicea.so /usr/lib/license
```

之后正常启动就行。

不过不知道上面的改动会不会给系统层面带来什么问题。。。我是chrome os下的子系统，坏了重启一个就是。。。如果是宿主系统。。。还请慎重。

**Comment by thd2020** [comment]
> 我使用上面的license信息成功登录了，解压后额外进行下面的操作。最后的`libuosdevicea.so`是软件包里本来就带的，因此直接软链接。
> 
> ```shell
> sudo mkdir -p /var/lib/uos-license /var/uos/ /usr/lib/license
> 
> sudo cp -r ./license/etc/os-release /etc/os-release
> sudo cp -r ./license/etc/lsb-release /etc/lsb-release
> sudo cp -r ./license/var/lib/uos-license/.license.json /var/lib/uos-license/.license.json
> sudo cp -r ./license/var/uos/.license.key /var/uos/
> 
> sudo ln -s /opt/apps/com.tencent.wechat/files/libuosdevicea.so /usr/lib/license
> ```
> 
> 之后正常启动就行。
> 
> 不过不知道上面的改动会不会给系统层面带来什么问题。。。我是chrome os下的子系统，坏了重启一个就是。。。如果是宿主系统。。。还请慎重。

我艹大佬牛b,整好了整好了。
不过这个```sudo ln -s /opt/apps/com.tencent.wechat/files/libuosdevicea.so /usr/lib/license```应该是```sudo ln -s /opt/apps/com.tencent.wechat/files/libuosdevicea.so /usr/lib/license/libuosdevicea.so```，好像漏了一点。
再次拜服大佬，祝大佬事业顺利。
