### ISSUE TITLE
debian11  arm64位无法运行

### ISSUE THREAD

**Issue by K7ISY4** [zydou/WeChat-AppImage#6]
运行提示”bash: ./WeChat-1.0.0.241-aarch64.AppImage：无法执行二进制文件: 可执行文件格式错误“，用file命令看了下，显示”WeChat-1.0.0.241-aarch64.AppImage: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=30e06184968532b6a9aa36f44ada39e4af0bda56, for GNU/Linux 2.6.32, stripped“，估计是架构方面的问题。

**Comment by zydou** [comment]
你试试 https://github.com/zydou/WeChat-AppImage/issues/4 里讨论的方案

**Comment by Jackhr-arch** [comment]
大概是appimage runtime的问题

我重新打包了一下，这是[文件](https://filetransfer.io/data-package/SSAS7HhJ#link)，`file`输出为`./Wechat-aarch64.AppImage: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=ecf4dd1f80c620b69e425775ac76171c6976b2c5, stripped`
你可以试一试
主要就是手动更换了一下[runtime](https://github.com/AppImage/AppImageKit/releases/download/13/AppRun-aarch64)

**Comment by K7ISY4** [comment]
可以运行了，十分感谢！

**Comment by K7ISY4** [comment]
> 大概是appimage runtime的问题
> 
> 我重新打包了一下，这是[文件](https://filetransfer.io/data-package/SSAS7HhJ#link)，`file`输出为`./Wechat-aarch64.AppImage: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=ecf4dd1f80c620b69e425775ac76171c6976b2c5, stripped` 你可以试一试 主要就是手动更换了一下[runtime](https://github.com/AppImage/AppImageKit/releases/download/13/AppRun-aarch64)

可以运行了，十分感谢！
