### ISSUE TITLE
ArchLinux x86_64 扫码登录无反应

### ISSUE THREAD

**Issue by Rvn0xsy** [zydou/WeChat-AppImage#7]
如题，安装完毕后微信可以正常打开，二维码也正常显示，但是手机扫码确认登录后，没有任何反应

![image](https://github.com/zydou/WeChat-AppImage/assets/19944759/47213800-cd11-41d4-a6d9-232cd194293d)

这个是不是我微信号有问题？

**Comment by zydou** [comment]
用的是哪个版本, 是AppImage还是tarball格式的, 系统架构是amd64还是arm64?

**Comment by Rvn0xsy** [comment]
> 用的是哪个版本, 是AppImage还是tarball格式的, 系统架构是amd64还是arm64?

我是通过AUR [wechat-universal-appimage](https://aur.archlinux.org/packages/wechat-universal-appimage) 这个包来安装的
- 安装命令：`yay -S wechat-universal-appimage`
- 系统是 `amd64`

**Comment by zydou** [comment]
AUR里的[wechat-universal-appimage](https://aur.archlinux.org/packages/wechat-universal-appimage)不是我维护的, 我不清楚为什么Upstream填成了这个仓库。

你可以试试直接下载本仓库提供的[AppImage](https://github.com/zydou/WeChat-AppImage/releases/latest)

**Comment by zydou** [comment]
BTW, 你还可以试试这个: https://aur.archlinux.org/packages/wechat-uos-bwrap

**Comment by Rvn0xsy** [comment]
> BTW, 你还可以试试这个: https://aur.archlinux.org/packages/wechat-uos-bwrap

这些我都尝试了，刚刚把本仓库的https://github.com/zydou/WeChat-AppImage/releases/latest 也运行了，手机扫码确认就是无反应。

> ~可能是我自己的微信问题~  我两个微信扫了都没反应

**Comment by zydou** [comment]
排查一下是不是网络问题，路由端DNS是否屏蔽了微信的相关域名？

**Comment by Rvn0xsy** [comment]
> 排查一下是不是网络问题，路由端DNS是否屏蔽了微信的相关域名？

感谢解惑，我抓包看了一下，我本地的DNS服务器确实有问题，换成别的就可以了。 
> 原因是： `wx.qlogo.cn`解析不正确
