### ISSUE TITLE
WeChat-1.0.0.241-aarch64.AppImage can not execute in ubuntu 

### ISSUE THREAD

**Issue by i0day** [zydou/WeChat-AppImage#8]
6.5.0-1025-oracle Ubuntu SMP aarch64 aarch64 aarch64 GNU/Linux
ubuntu mantic 23.10
./Downloads/WeChat-1.0.0.241-aarch64.AppImage 
bash: ./Downloads/WeChat-1.0.0.241-aarch64.AppImage: cannot execute binary file: Exec format error

我chmod +x Downloads/WeChat-1.0.0.241-aarch64.AppImage 
不能运行

**Comment by i0day** [comment]
在x86 arch linux 上
./Downloads/WeChat-1.0.0.241-x86_64.AppImage
libpng warning: iCCP: known incorrect sRGB profile
Failed to load /usr/lib/license/libuosdevicea.so.
我把libuosdevicea.so cope 到/usr/lib/license
还是报错

**Comment by zydou** [comment]
请尝试这里提到的方案: #4, #6

**Comment by i0day** [comment]
> 在x86 arch linux 上 ./Downloads/WeChat-1.0.0.241-x86_64.AppImage libpng warning: iCCP: known incorrect sRGB profile Failed to load /usr/lib/license/libuosdevicea.so. 我把libuosdevicea.so cope 到/usr/lib/license 还是报错

我最后安装了依赖库 openssl-1.1 x86 arch linux 正常运行

**Comment by i0day** [comment]
我在aarch64 ubuntu 23.10 的主机上运行了WeChat-1.0.0.241-aarch64.tar.xz 也是因为库openssl-1.1 不能登入。自己下载编译了openssl-1.1就可以了
